#!/bin/sh
set -e

case "$1" in
    configure)
    MYUSER=$( getent passwd 1000 | cut -d: -f1 )
    mkdir -p /etc/sddm.conf.d
    cat /usr/share/kosmos-autologin/autologin.conf.templ | sed "s/USERNAME/$MYUSER/" > /etc/sddm.conf.d/autologin.conf
    ;;

    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


#DEBHELPER#

exit 0
